# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 
auto: true
pygments: true
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

production_url : http://nanenj.github.com # or your custom domain name
title : nanenj.github.com

author :
  name : Nick Nadboralski
  email : nanenj@nomail.com
  github : nanenj
  twitter : nanenj
